//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Day defines model for Day.
type Day struct {
	// Date Example: 2026-10-10
	Date openapi_types.Date `json:"date"`

	// Id Example: 1
	Id     int     `json:"id"`
	Shifts []Shift `json:"shifts"`

	// Weekday Example: Samstag
	Weekday string `json:"weekday"`
}

// DeleteAssignmentRequest defines model for DeleteAssignmentRequest.
type DeleteAssignmentRequest struct {
	// AssignmentId Example: 501
	AssignmentId int `json:"assignmentId"`
}

// FileInfo defines model for FileInfo.
type FileInfo struct {
	// Description Example: Wichtige Richtlinien für die Lebensmittelzubereitung
	Description string `json:"description"`

	// Title Example: Hygienekonzept 2026
	Title string `json:"title"`

	// Url Example: https://example.com/files/hygiene.pdf
	Url string `json:"url"`
}

// FilesResponse defines model for FilesResponse.
type FilesResponse struct {
	Files []FileInfo `json:"files"`
}

// Shift defines model for Shift.
type Shift struct {
	// Description Example: Waffeln backen und Teig nachfüllen
	Description string `json:"description"`

	// EndTime Example: 12:00
	EndTime string `json:"endTime"`

	// Id Example: 101
	Id int `json:"id"`

	// RequiredSlots Example: 3
	RequiredSlots    int               `json:"required_slots"`
	ShiftAssignments []ShiftAssignment `json:"shift_assignments"`

	// StartTime Example: 09:00
	StartTime string `json:"startTime"`

	// Title Example: Frühschicht Waffelverkauf
	Title string `json:"title"`
}

// ShiftAssignment defines model for ShiftAssignment.
type ShiftAssignment struct {
	// Id Example: 501
	Id int `json:"id"`

	// Name Example: Erika Mustermann
	Name string `json:"name"`

	// PhoneNumber Example: +491701234567
	PhoneNumber string `json:"phoneNumber"`
}

// ShiftAssignmentRequest defines model for ShiftAssignmentRequest.
type ShiftAssignmentRequest struct {
	// Name Example: Max Mustermann
	Name string `json:"name"`

	// PhoneNumber Example: +4915198765432
	PhoneNumber string `json:"phoneNumber"`
}

// StandplanResponse defines model for StandplanResponse.
type StandplanResponse struct {
	Days []Day `json:"days"`
}

// WaffelnTotalResponse defines model for WaffelnTotalResponse.
type WaffelnTotalResponse struct {
	// WaffelnTotal Example: 142
	WaffelnTotal int `json:"waffelnTotal"`
}

// CreateWaffelEntryJSONBody defines parameters for CreateWaffelEntry.
type CreateWaffelEntryJSONBody = map[string]interface{}

// UpdateWaffelEntryJSONBody defines parameters for UpdateWaffelEntry.
type UpdateWaffelEntryJSONBody = map[string]interface{}

// DeleteShiftAssignmentJSONRequestBody defines body for DeleteShiftAssignment for application/json ContentType.
type DeleteShiftAssignmentJSONRequestBody = DeleteAssignmentRequest

// CreateShiftAssignmentJSONRequestBody defines body for CreateShiftAssignment for application/json ContentType.
type CreateShiftAssignmentJSONRequestBody = ShiftAssignmentRequest

// UpdateShiftAssignmentJSONRequestBody defines body for UpdateShiftAssignment for application/json ContentType.
type UpdateShiftAssignmentJSONRequestBody = ShiftAssignmentRequest

// CreateWaffelEntryJSONRequestBody defines body for CreateWaffelEntry for application/json ContentType.
type CreateWaffelEntryJSONRequestBody = CreateWaffelEntryJSONBody

// UpdateWaffelEntryJSONRequestBody defines body for UpdateWaffelEntry for application/json ContentType.
type UpdateWaffelEntryJSONRequestBody = UpdateWaffelEntryJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// GetStandplan Gesamten Standplan abrufen
	// (GET /standplan)
	GetStandplan(w http.ResponseWriter, r *http.Request)
	// GetStandplanFiles Dateien und Dokumente abrufen
	// (GET /standplan/files)
	GetStandplanFiles(w http.ResponseWriter, r *http.Request)
	// DeleteShiftAssignment Schichtbelegung löschen
	// (DELETE /standplan/shifts/{shiftId}/)
	DeleteShiftAssignment(w http.ResponseWriter, r *http.Request, shiftId int)
	// CreateShiftAssignment Schichtbelegung erstellen (wenn leer)
	// (POST /standplan/shifts/{shiftId}/)
	CreateShiftAssignment(w http.ResponseWriter, r *http.Request, shiftId int)
	// UpdateShiftAssignment Schichtbelegung aktualisieren
	// (PUT /standplan/shifts/{shiftId}/)
	UpdateShiftAssignment(w http.ResponseWriter, r *http.Request, shiftId int)
	// GetWaffelnTotal Gesamtanzahl der Waffeln abrufen
	// (GET /waffeln)
	GetWaffelnTotal(w http.ResponseWriter, r *http.Request)
	// CreateWaffelEntry Waffel-Zähler erhöhen/erstellen
	// (POST /waffeln)
	CreateWaffelEntry(w http.ResponseWriter, r *http.Request)
	// UpdateWaffelEntry Waffel-Zähler aktualisieren
	// (PUT /waffeln)
	UpdateWaffelEntry(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetStandplan operation middleware
func (siw *ServerInterfaceWrapper) GetStandplan(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetStandplan(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetStandplanFiles operation middleware
func (siw *ServerInterfaceWrapper) GetStandplanFiles(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetStandplanFiles(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteShiftAssignment operation middleware
func (siw *ServerInterfaceWrapper) DeleteShiftAssignment(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "shiftId" -------------
	var shiftId int

	err = runtime.BindStyledParameterWithOptions("simple", "shiftId", r.PathValue("shiftId"), &shiftId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "shiftId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteShiftAssignment(w, r, shiftId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateShiftAssignment operation middleware
func (siw *ServerInterfaceWrapper) CreateShiftAssignment(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "shiftId" -------------
	var shiftId int

	err = runtime.BindStyledParameterWithOptions("simple", "shiftId", r.PathValue("shiftId"), &shiftId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "shiftId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateShiftAssignment(w, r, shiftId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateShiftAssignment operation middleware
func (siw *ServerInterfaceWrapper) UpdateShiftAssignment(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "shiftId" -------------
	var shiftId int

	err = runtime.BindStyledParameterWithOptions("simple", "shiftId", r.PathValue("shiftId"), &shiftId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "shiftId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateShiftAssignment(w, r, shiftId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetWaffelnTotal operation middleware
func (siw *ServerInterfaceWrapper) GetWaffelnTotal(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetWaffelnTotal(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateWaffelEntry operation middleware
func (siw *ServerInterfaceWrapper) CreateWaffelEntry(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateWaffelEntry(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateWaffelEntry operation middleware
func (siw *ServerInterfaceWrapper) UpdateWaffelEntry(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateWaffelEntry(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/standplan", wrapper.GetStandplan)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/standplan/shifts/{shiftId}/{$}", wrapper.DeleteShiftAssignment)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/standplan/shifts/{shiftId}/{$}", wrapper.CreateShiftAssignment)
	m.HandleFunc(http.MethodPut+" "+options.BaseURL+"/standplan/shifts/{shiftId}/{$}", wrapper.UpdateShiftAssignment)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/waffeln", wrapper.GetWaffelnTotal)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/waffeln", wrapper.CreateWaffelEntry)
	m.HandleFunc(http.MethodPut+" "+options.BaseURL+"/waffeln", wrapper.UpdateWaffelEntry)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/standplan/files", wrapper.GetStandplanFiles)

	return m
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7Ffbbts4E34VQv9/0WIdS3YO3fou3bjdAOkiaNMt0G5R0NJIYk2NVJJK6gR+mzxDr3LnF1uQ1ME6JS66",
	"XexFbyJHmKFmvvnmm+GN46dJliKgks7sxpF+DAk1P0/oSj8ykWYgFAPzMqAK9BO+0CTj4MycqTc92pt4",
	"exPPGTlhKhKqnJm1GzlqlWkbqQTDyFmPHBY0vCeVCUMFEQhtI2MW2miYgsT8+L+A0Jk5/3PraN0iVPe1",
	"Ntd+xUlUCLrS/18BLAObRB3ua5pIRaNubOuRI+BzzgQEzuy9DrQ+YVTmU4T2ofJOF5/AN18/AQ4KjqVk",
	"ESaA6hV8zkGqLoS0MjltgnHo9cDRCqvh3BfGc8bhFMO0p3QgfcEyxVJsQvKW+bFiEZBX+gdnyABJuLkT",
	"JGBAzmABKBOmFPDrfAECmMox6iuuYoq32PH7KmKAsEzxGjJFNFn6PHPBm36xUpmcuW7xZuyniRsyDtKN",
	"7YnjLAi3CZcL9mBNbXyjBhL220NIylcgsxQldOE00exM0qosHZ62YrTH9sVjef4NZaVhCBzJgvpLQJJj",
	"QC6ARQSpH4ebO84B+0oBGFywpFXGyXTmebv0s9fb0WWCHyVPbWdXHvuDCvCx5vo3ikHdhH2yIBUVqpui",
	"93QgxR5WPxebu1j6se4XYnG+BLGkebibrpRErEOpce+g1eZrF5xBtmwB0eEN20F8Rg7SNk5zwZaUvMyl",
	"ApFQ7OVQFqcIf+TJAkTT+ZeDp5Mn3mS6f3B49GQ3rEwEzSN3yHdQfbsJvaRfviedw8nTX58cHR7sTx/M",
	"Z9dUFMUg4xSHxSegq9174sTy/l7ZMQf2BVOoyEWqKB+O52rLqikIB9MHZ1rDuRuDNmfFRGuInXN8fkqu",
	"c0H+BHFFuZ5K5DJF8to25p6RvALMzS0CEpleMSgadu/d5jbmIHBcNeSshp78lXve9Kiwlfo1OT4/dUbO",
	"JQhpPz8Ze2NPY5RmgDRjzszZH3vjfV1iqmIDjCvLE/V/EahuFmcMQhCKUM6BXNAICMMlzyW7BPNOlAkV",
	"Ih6AACTv8itgMscIUGOwufOXOhFdFKoP1ruF8wJUlZERFls/E9nU8/TDT1EV+kCzjDPfeLufpB0nlkMP",
	"qm6HsaZqzTznIkx5JID5MZDjRSh0qgFIUnnLseGGzJOEipWJX9JE513XhS5EHgIawxpct5rGvRC/YAtF",
	"gCGQMyZVCesliHBzFy2oxvOEKtB7z6PrMXk2JmfAVLi5DQBH5Nyw5/FuMJut4Udi3VxLdsdZ2BS5BqCN",
	"c5m8ptdJusy1gsIQ1HYHdm/M8zRYuxZvvf12kZ+jCkFggf4CpGJJoqCmr3uMCfBA9y7NpTGrCN9F2i7Z",
	"7dlm5QSkepYGq38M6KGFft3ULyVyWPfXuwlFlTKBukIECoDGWkgOvIP7/NKgxoag+RtBmGMA2K5oYbUA",
	"DpF25ZuvOi8044wKmoACIZ3Z+/bXThiQOcMAcnMlOD0hQbMgTFtpfStn88wpmOC0YRltIV1PhL6B8GHk",
	"ZKns6dy3wKQqWBEKQ9ISAMOocxAy1QrY5cpvAui/xZWB7WN3qvyIKPrEoQJvi4KGJCUBe4j7BqPNHTd0",
	"mDOM6AKaTLR3QkkuU84f4iEIqUBfPcijK0AkHEA8NqTMe6p/vFQ55UwyPR/1ZVQLFRZ00GICMWj2k9Zn",
	"umR4kwU/yTBAhq3i1KSIYHOLAQj1UEVpXaNyVhQL3f3jWJfTzneK1zTmRmcWTMZ2MuvLlAJ0I7D3V0BS",
	"Xmjvm8Pb6+qPnMK9a/G3LD3NJXRg89lCpky+GspDijkX8eZrrEhQIVZ+xHatBHVt0JeABGFQOK3vHJVY",
	"fUefVLJ/s+5Z7Nf/gQq1MNrugS1qd9qg46ZRB3QrgdtR1DpVMovWkID9LMqwMLV82rq0Xv8dAAD//w==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
