//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// CreateShiftAssignmentResponse defines model for CreateShiftAssignmentResponse.
type CreateShiftAssignmentResponse struct {
	// Id Example: 501
	Id int `json:"id"`
}

// Day defines model for Day.
type Day struct {
	// Date Example: 2026-10-10
	Date openapi_types.Date `json:"date"`

	// Id Example: 1
	Id     int     `json:"id"`
	Shifts []Shift `json:"shifts"`

	// Weekday Example: Samstag
	Weekday string `json:"weekday"`
}

// DeleteAssignmentRequest defines model for DeleteAssignmentRequest.
type DeleteAssignmentRequest struct {
	// AssignmentId Example: 501
	AssignmentId int `json:"assignmentId"`
}

// FileInfo defines model for FileInfo.
type FileInfo struct {
	// Description Example: Wichtige Richtlinien für die Lebensmittelzubereitung
	Description string `json:"description"`

	// Title Example: Hygienekonzept 2026
	Title string `json:"title"`

	// Url Example: https://example.com/files/hygiene.pdf
	Url string `json:"url"`
}

// FilesResponse defines model for FilesResponse.
type FilesResponse struct {
	Files []FileInfo `json:"files"`
}

// Shift defines model for Shift.
type Shift struct {
	// Description Example: Waffeln backen und Teig nachfüllen
	Description string `json:"description"`

	// EndTime Example: 12:00
	EndTime string `json:"endTime"`

	// Id Example: 101
	Id int `json:"id"`

	// RequiredSlots Example: 3
	RequiredSlots    int               `json:"required_slots"`
	ShiftAssignments []ShiftAssignment `json:"shift_assignments"`

	// StartTime Example: 09:00
	StartTime string `json:"startTime"`

	// Title Example: Frühschicht Waffelverkauf
	Title string `json:"title"`
}

// ShiftAssignment defines model for ShiftAssignment.
type ShiftAssignment struct {
	// Id Example: 501
	Id int `json:"id"`

	// Name Example: Erika Mustermann
	Name string `json:"name"`

	// PhoneNumber Example: +491701234567
	PhoneNumber string `json:"phoneNumber"`
}

// ShiftAssignmentRequest defines model for ShiftAssignmentRequest.
type ShiftAssignmentRequest struct {
	// Name Example: Max Mustermann
	Name string `json:"name"`

	// PhoneNumber Example: +4915198765432
	PhoneNumber string `json:"phoneNumber"`
}

// StandplanResponse defines model for StandplanResponse.
type StandplanResponse struct {
	Days []Day `json:"days"`
}

// WaffelnTotalResponse defines model for WaffelnTotalResponse.
type WaffelnTotalResponse struct {
	// WaffelnTotal Example: 142
	WaffelnTotal int `json:"waffelnTotal"`
}

// CreateWaffelEntryJSONBody defines parameters for CreateWaffelEntry.
type CreateWaffelEntryJSONBody = map[string]interface{}

// UpdateWaffelEntryJSONBody defines parameters for UpdateWaffelEntry.
type UpdateWaffelEntryJSONBody = map[string]interface{}

// DeleteShiftAssignmentJSONRequestBody defines body for DeleteShiftAssignment for application/json ContentType.
type DeleteShiftAssignmentJSONRequestBody = DeleteAssignmentRequest

// CreateShiftAssignmentJSONRequestBody defines body for CreateShiftAssignment for application/json ContentType.
type CreateShiftAssignmentJSONRequestBody = ShiftAssignmentRequest

// UpdateShiftAssignmentJSONRequestBody defines body for UpdateShiftAssignment for application/json ContentType.
type UpdateShiftAssignmentJSONRequestBody = ShiftAssignmentRequest

// CreateWaffelEntryJSONRequestBody defines body for CreateWaffelEntry for application/json ContentType.
type CreateWaffelEntryJSONRequestBody = CreateWaffelEntryJSONBody

// UpdateWaffelEntryJSONRequestBody defines body for UpdateWaffelEntry for application/json ContentType.
type UpdateWaffelEntryJSONRequestBody = UpdateWaffelEntryJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// GetStandplan Gesamten Standplan abrufen
	// (GET /standplan)
	GetStandplan(w http.ResponseWriter, r *http.Request)
	// GetStandplanFiles Dateien und Dokumente abrufen
	// (GET /standplan/files)
	GetStandplanFiles(w http.ResponseWriter, r *http.Request)
	// DeleteShiftAssignment Schichtbelegung löschen
	// (DELETE /standplan/shifts/{shiftId}/)
	DeleteShiftAssignment(w http.ResponseWriter, r *http.Request, shiftId int)
	// CreateShiftAssignment Schichtbelegung erstellen (wenn leer)
	// (POST /standplan/shifts/{shiftId}/)
	CreateShiftAssignment(w http.ResponseWriter, r *http.Request, shiftId int)
	// UpdateShiftAssignment Schichtbelegung aktualisieren
	// (PUT /standplan/shifts/{shiftId}/)
	UpdateShiftAssignment(w http.ResponseWriter, r *http.Request, shiftId int)
	// GetWaffelnTotal Gesamtanzahl der Waffeln abrufen
	// (GET /waffeln)
	GetWaffelnTotal(w http.ResponseWriter, r *http.Request)
	// CreateWaffelEntry Waffel-Zähler erhöhen/erstellen
	// (POST /waffeln)
	CreateWaffelEntry(w http.ResponseWriter, r *http.Request)
	// UpdateWaffelEntry Waffel-Zähler aktualisieren
	// (PUT /waffeln)
	UpdateWaffelEntry(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetStandplan operation middleware
func (siw *ServerInterfaceWrapper) GetStandplan(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetStandplan(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetStandplanFiles operation middleware
func (siw *ServerInterfaceWrapper) GetStandplanFiles(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetStandplanFiles(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteShiftAssignment operation middleware
func (siw *ServerInterfaceWrapper) DeleteShiftAssignment(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "shiftId" -------------
	var shiftId int

	err = runtime.BindStyledParameterWithOptions("simple", "shiftId", r.PathValue("shiftId"), &shiftId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "shiftId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteShiftAssignment(w, r, shiftId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateShiftAssignment operation middleware
func (siw *ServerInterfaceWrapper) CreateShiftAssignment(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "shiftId" -------------
	var shiftId int

	err = runtime.BindStyledParameterWithOptions("simple", "shiftId", r.PathValue("shiftId"), &shiftId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "shiftId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateShiftAssignment(w, r, shiftId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateShiftAssignment operation middleware
func (siw *ServerInterfaceWrapper) UpdateShiftAssignment(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "shiftId" -------------
	var shiftId int

	err = runtime.BindStyledParameterWithOptions("simple", "shiftId", r.PathValue("shiftId"), &shiftId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "shiftId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateShiftAssignment(w, r, shiftId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetWaffelnTotal operation middleware
func (siw *ServerInterfaceWrapper) GetWaffelnTotal(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetWaffelnTotal(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateWaffelEntry operation middleware
func (siw *ServerInterfaceWrapper) CreateWaffelEntry(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateWaffelEntry(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateWaffelEntry operation middleware
func (siw *ServerInterfaceWrapper) UpdateWaffelEntry(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateWaffelEntry(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/standplan", wrapper.GetStandplan)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/standplan/shifts/{shiftId}/{$}", wrapper.DeleteShiftAssignment)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/standplan/shifts/{shiftId}/{$}", wrapper.CreateShiftAssignment)
	m.HandleFunc(http.MethodPut+" "+options.BaseURL+"/standplan/shifts/{shiftId}/{$}", wrapper.UpdateShiftAssignment)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/waffeln", wrapper.GetWaffelnTotal)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/waffeln", wrapper.CreateWaffelEntry)
	m.HandleFunc(http.MethodPut+" "+options.BaseURL+"/waffeln", wrapper.UpdateWaffelEntry)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/standplan/files", wrapper.GetStandplanFiles)

	return m
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7FjNbttGEH6VxbaHBJVFSv5Jo5tTO6kBpzASpwGSBsFKHJIbLYfM7tKObOht/Aw5+aYXK3aXIsU/W24S",
	"oEB7sSRiZjnzzTffzPqaztIkSxFQKzq5pmoWQ8Ls198kMA2vYx7qQ6V4hAmgfgUqS1GBMchkmoHUHKw5",
	"D8xf+MKSTACd7PujAdWLDOiEctQQgaTL5YBK+JxzCQGdvDcuH0qjdPoJZpouB/SILdrHB0xD7QV07I8P",
	"dkb+zsinAxqmMmGaTpxdeajSkmNkDm2E1xHcgCqTq0tGQ2K//CwhpBP6k1fB5BUYeRYa41ecxKRkC/P7",
	"EmAeuCSqcF+zRGkWtWNrg1KdMFjnU4TWCRcI0LBZos85KN2GkJUmJw+vVc25K4znXMAJhmlH6UDNJM80",
	"T7EOyVs+izWPgLwyXwRHDkjC1a0kAQdyClNAlXCtQVzlU5DAdY5RV3E116LBjt8XEQeEeYpXkGliyNLl",
	"mUtR94u1ztTE84onw1maeCEXoLzYnTjMgnCTcLnk99bUxTeoIeHe3Yek6m80G83WJC3L0uJpI0Z3bFc8",
	"jucPKCsLQxBIpmw2ByQ5BuQceESQzeJwdSsEYFcpAINznjTKOBpPfH+bfvY7O3qd4EclUtfZpcdurwJ8",
	"rLj+QDGomrBLFpRmUrdT9J/2pNjB6udydRurWWz6hTicL0DOWR5upytrIlahVLi30GrytQ1OL1s2gPhH",
	"g2JAkTVxOpZ8zsjLXGmQCcNODmVxivBHnkxB1p1/2Xs6euKPxrt7+wdPtsPKRlA/cot8e9W3ndBL9uVb",
	"0tkfPf31ycH+3u743ny2TUUzDDLBsF98ArbYvieOHO/vlB17YFcwhYqcp5qJ/nguN6zqgrA3vnem1Zzb",
	"MRhzXky0mtjRw7MTcpVL8ifISybMVCIXKZLXrjF3rOQVYK5uEJCo9JJD0bA771Y3sQCJw7IhJxX05K/c",
	"98cHha0yj8nh2Qkd0AuQyr1+NPSHvsEozQBZxumE7g794a4pMdOxBcZT6xPNrwh0O4tTDiFITZgQQM5Z",
	"BITjXOSKX4B9JtcJFSIegAQk7/JL4CrHCNBgsLqdzU0ipijMHGx2C/oCdJmRFRZXPxvZ2PfNxyxFXegD",
	"yzLBZ9bb+6TcOHEculd1W4y1VavneSzDVEQS+CwGcjgNpUk1AEVKbzW03FB5kjC5sPErlpi8q7qwqcxD",
	"QGtYgeuV07gT4hd8qglwBHLKlV7DegEyXN1GU2bwPGIazN7z6GpIng3JKXAdrm4CwAE5s+x5vB3Mdmv4",
	"kVjX15LtcZYuRWEAaOK8Tt7Q6yid50ZBoQ9qtwN71/bzJFh6Dm+z/baRP0YdgsQC/SkozZNEQ0Vf7xAT",
	"EIHpXZYra1YSvo20W7Kbs83JCSj9LA0W3w3ovoV+WdcvLXNYdte7DkWZMoGqQgQKgIZGSPb8vbv80qDC",
	"hqD9G0GYYwDYrGhhNQUBkXEVq68mL7TjjEmWgAap6OR9821HHMgxxwByeyU4OSJBvSDcWBl9W8/mCS2Y",
	"QJuwDDaQriZC10D4MKBZqjo69y1wpQtWhNKSdA2AZdQZSJUaBWxzpfPi/IO40rN9bE+V7xLF3f8q6JCK",
	"EsoNQlrKrOnYQeM3GK1uhSXHMceITaHOS3dDVOQiFeI+VoJUGsxFhDy6BEQiAORjS9G8gwuHc50zwRU3",
	"09JcTY1sYUEOIy0Qg+kF0nhNmxpvsuA/Ro3WvaiXDBvFqUgRweoGA5D6voqyqkbryVGsd3cPZ1NON+0Z",
	"XrFYWNWZchW7OW2uVhrQi8DdZgHJ+np711TeXF5/5EzuXJIfsgLVV9KePWgDmXXy5Yju089jGa++xpoE",
	"JWLrl7iuVaCvLPoKkCD0yqjzPUYtF9/QJ+UQuF52rPnLf0GFGhht9sAGtVtt0HIzqAN6pcBtKWqtKtm1",
	"q0/A/i9KvzA1fJq6tFz+HQAA//8=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
