//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// CreateShiftAssignmentResponse defines model for CreateShiftAssignmentResponse.
type CreateShiftAssignmentResponse struct {
	// Id Example: 501
	Id int `json:"id"`
}

// Day defines model for Day.
type Day struct {
	// Date Example: 2026-10-10
	Date openapi_types.Date `json:"date"`

	// Id Example: 1
	Id     int     `json:"id"`
	Shifts []Shift `json:"shifts"`

	// Weekday Example: Samstag
	Weekday string `json:"weekday"`
}

// FileInfo defines model for FileInfo.
type FileInfo struct {
	// Description Example: Wichtige Richtlinien für die Lebensmittelzubereitung
	Description string `json:"description"`

	// Title Example: Hygienekonzept 2026
	Title string `json:"title"`

	// Url Example: https://example.com/files/hygiene.pdf
	Url string `json:"url"`
}

// FilesResponse defines model for FilesResponse.
type FilesResponse struct {
	Files []FileInfo `json:"files"`
}

// Shift defines model for Shift.
type Shift struct {
	// Description Example: Waffeln backen und Teig nachfüllen
	Description string `json:"description"`

	// EndTime Example: 12:00
	EndTime string `json:"endTime"`

	// Id Example: 101
	Id int `json:"id"`

	// RequiredSlots Example: 3
	RequiredSlots    int                       `json:"required_slots"`
	ShiftAssignments []ShiftAssignmentResponse `json:"shift_assignments"`

	// StartTime Example: 09:00
	StartTime string `json:"startTime"`

	// Title Example: Frühschicht Waffelverkauf
	Title string `json:"title"`
}

// ShiftAssignmentRequest defines model for ShiftAssignmentRequest.
type ShiftAssignmentRequest struct {
	// Name Example: Max Mustermann
	Name string `json:"name"`

	// PhoneNumber Example: +4915198765432
	PhoneNumber string `json:"phoneNumber"`
}

// ShiftAssignmentResponse defines model for ShiftAssignmentResponse.
type ShiftAssignmentResponse struct {
	// Id Example: 501
	Id int `json:"id"`

	// Name Example: Max Mustermann
	Name string `json:"name"`

	// PhoneNumber Example: +4915198765432
	PhoneNumber string `json:"phoneNumber"`
}

// StandplanResponse defines model for StandplanResponse.
type StandplanResponse struct {
	Days []Day `json:"days"`
}

// WaffelnTotalResponse defines model for WaffelnTotalResponse.
type WaffelnTotalResponse struct {
	// WaffelnTotal Example: 142
	WaffelnTotal int `json:"waffelnTotal"`
}

// CreateWaffelEntryJSONBody defines parameters for CreateWaffelEntry.
type CreateWaffelEntryJSONBody = map[string]interface{}

// UpdateWaffelEntryJSONBody defines parameters for UpdateWaffelEntry.
type UpdateWaffelEntryJSONBody = map[string]interface{}

// CreateShiftAssignmentJSONRequestBody defines body for CreateShiftAssignment for application/json ContentType.
type CreateShiftAssignmentJSONRequestBody = ShiftAssignmentRequest

// UpdateShiftAssignmentJSONRequestBody defines body for UpdateShiftAssignment for application/json ContentType.
type UpdateShiftAssignmentJSONRequestBody = ShiftAssignmentRequest

// CreateWaffelEntryJSONRequestBody defines body for CreateWaffelEntry for application/json ContentType.
type CreateWaffelEntryJSONRequestBody = CreateWaffelEntryJSONBody

// UpdateWaffelEntryJSONRequestBody defines body for UpdateWaffelEntry for application/json ContentType.
type UpdateWaffelEntryJSONRequestBody = UpdateWaffelEntryJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// GetStandplan Gesamten Standplan abrufen
	// (GET /standplan)
	GetStandplan(w http.ResponseWriter, r *http.Request)
	// GetStandplanFiles Dateien und Dokumente abrufen
	// (GET /standplan/files)
	GetStandplanFiles(w http.ResponseWriter, r *http.Request)
	// CreateShiftAssignment Schichtbelegung erstellen (wenn leer)
	// (POST /standplan/shifts/{shiftId}/assignments)
	CreateShiftAssignment(w http.ResponseWriter, r *http.Request, shiftId int)
	// DeleteShiftAssignment Schichtbelegung löschen
	// (DELETE /standplan/shifts/{shiftId}/assignments/{assignmentId})
	DeleteShiftAssignment(w http.ResponseWriter, r *http.Request, shiftId int, assignmentId int)
	// UpdateShiftAssignment Schichtbelegung aktualisieren
	// (PUT /standplan/shifts/{shiftId}/assignments/{assignmentId})
	UpdateShiftAssignment(w http.ResponseWriter, r *http.Request, shiftId int, assignmentId int)
	// GetWaffelnTotal Gesamtanzahl der Waffeln abrufen
	// (GET /waffeln)
	GetWaffelnTotal(w http.ResponseWriter, r *http.Request)
	// CreateWaffelEntry Waffel-Zähler erhöhen/erstellen
	// (POST /waffeln)
	CreateWaffelEntry(w http.ResponseWriter, r *http.Request)
	// UpdateWaffelEntry Waffel-Zähler aktualisieren
	// (PUT /waffeln)
	UpdateWaffelEntry(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetStandplan operation middleware
func (siw *ServerInterfaceWrapper) GetStandplan(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetStandplan(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetStandplanFiles operation middleware
func (siw *ServerInterfaceWrapper) GetStandplanFiles(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetStandplanFiles(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateShiftAssignment operation middleware
func (siw *ServerInterfaceWrapper) CreateShiftAssignment(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "shiftId" -------------
	var shiftId int

	err = runtime.BindStyledParameterWithOptions("simple", "shiftId", r.PathValue("shiftId"), &shiftId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "shiftId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateShiftAssignment(w, r, shiftId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteShiftAssignment operation middleware
func (siw *ServerInterfaceWrapper) DeleteShiftAssignment(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "shiftId" -------------
	var shiftId int

	err = runtime.BindStyledParameterWithOptions("simple", "shiftId", r.PathValue("shiftId"), &shiftId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "shiftId", Err: err})
		return
	}

	// ------------- Path parameter "assignmentId" -------------
	var assignmentId int

	err = runtime.BindStyledParameterWithOptions("simple", "assignmentId", r.PathValue("assignmentId"), &assignmentId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "assignmentId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteShiftAssignment(w, r, shiftId, assignmentId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateShiftAssignment operation middleware
func (siw *ServerInterfaceWrapper) UpdateShiftAssignment(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "shiftId" -------------
	var shiftId int

	err = runtime.BindStyledParameterWithOptions("simple", "shiftId", r.PathValue("shiftId"), &shiftId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "shiftId", Err: err})
		return
	}

	// ------------- Path parameter "assignmentId" -------------
	var assignmentId int

	err = runtime.BindStyledParameterWithOptions("simple", "assignmentId", r.PathValue("assignmentId"), &assignmentId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "assignmentId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateShiftAssignment(w, r, shiftId, assignmentId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetWaffelnTotal operation middleware
func (siw *ServerInterfaceWrapper) GetWaffelnTotal(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetWaffelnTotal(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateWaffelEntry operation middleware
func (siw *ServerInterfaceWrapper) CreateWaffelEntry(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateWaffelEntry(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateWaffelEntry operation middleware
func (siw *ServerInterfaceWrapper) UpdateWaffelEntry(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateWaffelEntry(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/standplan", wrapper.GetStandplan)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/standplan/shifts/{shiftId}/assignments", wrapper.CreateShiftAssignment)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/standplan/shifts/{shiftId}/assignments/{assignmentId}", wrapper.DeleteShiftAssignment)
	m.HandleFunc(http.MethodPut+" "+options.BaseURL+"/standplan/shifts/{shiftId}/assignments/{assignmentId}", wrapper.UpdateShiftAssignment)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/waffeln", wrapper.GetWaffelnTotal)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/waffeln", wrapper.CreateWaffelEntry)
	m.HandleFunc(http.MethodPut+" "+options.BaseURL+"/waffeln", wrapper.UpdateWaffelEntry)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/standplan/files", wrapper.GetStandplanFiles)

	return m
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7Fjdbtu4En4VgudctDiOpfy059R36UnaNZAugjbdAu0WBW2NJNbUSCWppE7gt8kz9Cp3frEFSVn/ih10",
	"i+0Ce+M/kNQ333zzzdA3dJ4mWYqAWtHJDVXzGBJmP/5fAtPwJuahPlaKR5gA6tegshQVmAWZTDOQmoNd",
	"zgPzCl9Zkgmgkyf+/ojqZQZ0QjlqiEDS1WpEJXzJuYSATj6YLR/LRensM8w1XY3oCVt2jw+YhsYD6IF/",
	"8HRv39/b9+mIhqlMmKYTt648VGnJMTKHtuD1gBtRZWJ1wWhI7Id/SwjphP7Lq2jyCo48S43ZV5zEpGRL",
	"8/0KYBG4ICq4b1iiNIu62LqkVCeMNvEU0ProesEFTDFMezgDNZc80zzFJpZ3fB5rHgF5bT4IjhyQhOs7",
	"SQIO5AxmgCrhWoO4zmcggescoz5WNdeilZZflhEHhEWK15BpYrLUtzOXorkv1jpTE88rfhnP08QLuQDl",
	"xe7EcRaE9Uznkm8l0+EbNZhwzx5iUg0r3KLZWR1lWjoCaWF0x/bhcQJ7QFpZGIJAMmPzBSDJMSAXwCOC",
	"bB6H6zshAPtSARhc8KSVxv2Die/vUkh+byltAvykROpKqtxxOFh6n1jpMw+swh6D6qlLpZnU3VD9ZwOh",
	"9qj7hVzfxWoem7ohju9LkAuWh7sV9kaQFZSK/w5rbd12SRpUTZ2QLzmoHhkhaxPxin0lr3KlQSYMe6WS",
	"xSnCr3kyA9nc+p+jZ/tP9p/9779PnxwdHmzlwj67edxOoXxP8xn9pRHb7O8atmYYZILhcMABW+5eIidO",
	"/ve6kD2wD0xhKhepZmIYz1VtVdMfjg62zgGNzV0MZjkvGlzD++jx+ZRc55L8BvKKCdOkyGWK5I2rzz3r",
	"gAWZ61sEJCq94lDU7d779W0sQOK4rMtJRT35Pff9g6fFWmV+JsfnUzqilyCVe/z+2B/7hqM0A2QZpxN6",
	"OPbHhybFTMeWGE9tTjTfItDdKM44hCA1YUIAuWAREI4LkSt+CfY3uQmo8PQAJCB5n18BVzlGgIaD9d18",
	"YQIxSWHm4GlAJ/Ql6DIi6y8ufxbZge+bt3mKGtDCYlkm+Nzu9j4r112chraacEexNmvNOE9lmIpIAp/H",
	"QI5noTShBqBIuVuNrTZUniRMLi1+xRITd5UXNpN5CGgXVuR6ZXPupfgln2kCHIGccaU3tF6CDNd30YwZ",
	"Pk+YBjMGPboek+djcgZch+vbAHBEzq16Hu9Gsx0ifiTXzSlld56lC1EYAto8b4I38jpJF7lxWxii2s2i",
	"3o19nwYrz9oBkywBDVLRyYc2/SccyCnHAHI7dU5PLJxC1YZOblaZmtmY5IQWp9O6VWiZw6hGU+UyfSbz",
	"cQvs1rTxM0YwolmqevT8DrhygpYklDZ1BRan8nOQKjW+0NVq77WuwAhKP0+D5Z9nC/2jyKrZAAwnqx9Y",
	"MPdfZHsKqKSyKiQyAwGRHhu3P3LYmnveYrS+E1YcpxwjNgOS1iRC3DVKkctUiHb1FWvsI0wPA6k0mGmd",
	"PLoCRCIA5OOtVViTs3dTfZkGK4dWgLtBt8wCdQgSC93MQGmeJBqq9uIdYwIiMLhYrgrN1YTfVNeJfczu",
	"6sJciIHcN3GWeBpZgQJ9kZej+/Y10oH2NYIwxwBwW0LE+psRE9qB8OezidGDYGyiGoBTV853Wlfe41zH",
	"C50zwRU3E0/AwTYlLGRl5AcxmJT0oW1K7W0W/H2MrNdgagVfSTqC9S0GIPU2UbKKyU2PLgbp+8cgQ7qb",
	"qxhes1hYbcy4it1EZO6yGtCLwP2NAEg2/yvcN//Urwk/cvrpvY48ZNhsDv8DE2eNmU3w5TA01JNPZbz+",
	"FmsSlIxtHuKsR4G+tuwrQIIw2Jrd3lPUcvkdai6r82bVc6Fa/QQZanFUr4GatDtl0NlmWAf0yqZpM7Td",
	"ejpZsq11yGb+ScqwMbX2tH1ptfojAAD//w==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
