DROP TABLE IF EXISTS shift_assignments CASCADE;
DROP TABLE IF EXISTS roles CASCADE;
DROP TABLE IF EXISTS volunteers CASCADE;
DROP TABLE IF EXISTS shifts CASCADE;
DROP TABLE IF EXISTS market_days CASCADE;
DROP TABLE IF EXISTS weekends CASCADE;
DROP TABLE IF EXISTS editions CASCADE;