//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for AssignmentCreateStatus.
const (
	AssignmentCreateStatusCancelled AssignmentCreateStatus = "cancelled"
	AssignmentCreateStatusConfirmed AssignmentCreateStatus = "confirmed"
	AssignmentCreateStatusPending   AssignmentCreateStatus = "pending"
)

// Valid indicates whether the value is a known member of the AssignmentCreateStatus enum.
func (e AssignmentCreateStatus) Valid() bool {
	switch e {
	case AssignmentCreateStatusCancelled:
		return true
	case AssignmentCreateStatusConfirmed:
		return true
	case AssignmentCreateStatusPending:
		return true
	default:
		return false
	}
}

// Defines values for AssignmentUpdateStatus.
const (
	AssignmentUpdateStatusCancelled AssignmentUpdateStatus = "cancelled"
	AssignmentUpdateStatusConfirmed AssignmentUpdateStatus = "confirmed"
	AssignmentUpdateStatusPending   AssignmentUpdateStatus = "pending"
)

// Valid indicates whether the value is a known member of the AssignmentUpdateStatus enum.
func (e AssignmentUpdateStatus) Valid() bool {
	switch e {
	case AssignmentUpdateStatusCancelled:
		return true
	case AssignmentUpdateStatusConfirmed:
		return true
	case AssignmentUpdateStatusPending:
		return true
	default:
		return false
	}
}

// Defines values for ShiftAssignmentStatus.
const (
	ShiftAssignmentStatusCancelled ShiftAssignmentStatus = "cancelled"
	ShiftAssignmentStatusConfirmed ShiftAssignmentStatus = "confirmed"
	ShiftAssignmentStatusPending   ShiftAssignmentStatus = "pending"
)

// Valid indicates whether the value is a known member of the ShiftAssignmentStatus enum.
func (e ShiftAssignmentStatus) Valid() bool {
	switch e {
	case ShiftAssignmentStatusCancelled:
		return true
	case ShiftAssignmentStatusConfirmed:
		return true
	case ShiftAssignmentStatusPending:
		return true
	default:
		return false
	}
}

// Defines values for StandplanDayDayOfWeek.
const (
	Freitag StandplanDayDayOfWeek = "Freitag"
	Samstag StandplanDayDayOfWeek = "Samstag"
	Sonntag StandplanDayDayOfWeek = "Sonntag"
)

// Valid indicates whether the value is a known member of the StandplanDayDayOfWeek enum.
func (e StandplanDayDayOfWeek) Valid() bool {
	switch e {
	case Freitag:
		return true
	case Samstag:
		return true
	case Sonntag:
		return true
	default:
		return false
	}
}

// AssignmentCreate defines model for AssignmentCreate.
type AssignmentCreate struct {
	// RoleId Example: 2
	RoleId *int                    `json:"roleId,omitempty"`
	Status *AssignmentCreateStatus `json:"status,omitempty"`

	// VolunteerId Example: 5
	VolunteerId int `json:"volunteerId"`
}

// AssignmentCreateStatus defines model for AssignmentCreate.Status.
type AssignmentCreateStatus string

// AssignmentUpdate defines model for AssignmentUpdate.
type AssignmentUpdate struct {
	RoleId *int                    `json:"roleId,omitempty"`
	Status *AssignmentUpdateStatus `json:"status,omitempty"`
}

// AssignmentUpdateStatus defines model for AssignmentUpdate.Status.
type AssignmentUpdateStatus string

// Edition defines model for Edition.
type Edition struct {
	CreatedAt *time.Time `json:"createdAt,omitempty"`

	// Id Example: 1
	Id *int `json:"id,omitempty"`

	// IsActive Example: true
	IsActive *bool `json:"isActive,omitempty"`

	// Name Example: Weihnachtsmarkt 2026
	Name *string `json:"name,omitempty"`

	// Year Example: 2026
	Year *int `json:"year,omitempty"`
}

// EditionCreate defines model for EditionCreate.
type EditionCreate struct {
	IsActive *bool `json:"isActive,omitempty"`

	// Name Example: Weihnachtsmarkt 2026
	Name string `json:"name"`

	// Year Example: 2026
	Year int `json:"year"`
}

// EditionUpdate defines model for EditionUpdate.
type EditionUpdate struct {
	IsActive *bool   `json:"isActive,omitempty"`
	Name     *string `json:"name,omitempty"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	// Error Example: NOT_FOUND
	Error string `json:"error"`

	// Message Example: Die gesuchte Schicht existiert nicht.
	Message string `json:"message"`
}

// Role defines model for Role.
type Role struct {
	// Description Example: Kassieren, Wechselgeld verwalten und Abrechnung
	Description *string `json:"description,omitempty"`

	// Id Example: 2
	Id *int `json:"id,omitempty"`

	// Name Example: Kasse & Verkauf
	Name *string `json:"name,omitempty"`
}

// RoleCreate defines model for RoleCreate.
type RoleCreate struct {
	Description *string `json:"description,omitempty"`

	// Name Example: Waffeleisen
	Name string `json:"name"`
}

// Shift defines model for Shift.
type Shift struct {
	DayId *int `json:"dayId,omitempty"`

	// EndTime Example: 17:30:00
	EndTime *string `json:"endTime,omitempty"`

	// Id Example: 10
	Id *int `json:"id,omitempty"`

	// Notes Example: Bitte 15 Minuten vor Beginn da sein!
	Notes *string `json:"notes,omitempty"`

	// RequiredSlots Example: 4
	RequiredSlots *int `json:"requiredSlots,omitempty"`

	// StartTime Example: 14:00:00
	StartTime *string `json:"startTime,omitempty"`

	// Title Example: Aufbau & Frühschicht
	Title *string `json:"title,omitempty"`
}

// ShiftAssignment defines model for ShiftAssignment.
type ShiftAssignment struct {
	AssignedAt *time.Time `json:"assignedAt,omitempty"`

	// Id Example: 101
	Id      *int  `json:"id,omitempty"`
	Role    *Role `json:"role,omitempty"`
	RoleId  *int  `json:"roleId,omitempty"`
	ShiftId *int  `json:"shiftId,omitempty"`

	// Status Example: confirmed
	Status      *ShiftAssignmentStatus `json:"status,omitempty"`
	Volunteer   *Volunteer             `json:"volunteer,omitempty"`
	VolunteerId *int                   `json:"volunteerId,omitempty"`
}

// ShiftAssignmentStatus Example: confirmed
type ShiftAssignmentStatus string

// ShiftCreate defines model for ShiftCreate.
type ShiftCreate struct {
	// EndTime Example: 21:30
	EndTime string  `json:"endTime"`
	Notes   *string `json:"notes,omitempty"`

	// RequiredSlots Example: 3
	RequiredSlots int `json:"requiredSlots"`

	// StartTime Example: 18:00
	StartTime string `json:"startTime"`

	// Title Example: Spätschicht Glühwein
	Title string `json:"title"`
}

// ShiftDetail defines model for ShiftDetail.
type ShiftDetail struct {
	Assignments *[]ShiftAssignment `json:"assignments,omitempty"`
	DayId       *int               `json:"dayId,omitempty"`

	// EndTime Example: 17:30:00
	EndTime *string `json:"endTime,omitempty"`

	// FreeSlots Example: 1
	FreeSlots *int `json:"freeSlots,omitempty"`

	// Id Example: 10
	Id *int `json:"id,omitempty"`

	// Notes Example: Bitte 15 Minuten vor Beginn da sein!
	Notes *string `json:"notes,omitempty"`

	// OccupiedSlots Example: 3
	OccupiedSlots *int `json:"occupiedSlots,omitempty"`

	// RequiredSlots Example: 4
	RequiredSlots *int `json:"requiredSlots,omitempty"`

	// StartTime Example: 14:00:00
	StartTime *string `json:"startTime,omitempty"`

	// Title Example: Aufbau & Frühschicht
	Title *string `json:"title,omitempty"`
}

// StandplanDay defines model for StandplanDay.
type StandplanDay struct {
	// Date Example: 2026-11-27
	Date      *openapi_types.Date    `json:"date,omitempty"`
	DayOfWeek *StandplanDayDayOfWeek `json:"dayOfWeek,omitempty"`
	Id        *int                   `json:"id,omitempty"`
	Shifts    *[]ShiftDetail         `json:"shifts,omitempty"`
}

// StandplanDayDayOfWeek defines model for StandplanDay.DayOfWeek.
type StandplanDayDayOfWeek string

// StandplanResponse defines model for StandplanResponse.
type StandplanResponse struct {
	Edition  *Edition            `json:"edition,omitempty"`
	Weekends *[]StandplanWeekend `json:"weekends,omitempty"`
}

// StandplanWeekend defines model for StandplanWeekend.
type StandplanWeekend struct {
	Days *[]StandplanDay `json:"days,omitempty"`
	Id   *int            `json:"id,omitempty"`

	// Label Example: 1. Adventswochenende
	Label *string `json:"label,omitempty"`

	// WeekendNumber Example: 1
	WeekendNumber *int `json:"weekendNumber,omitempty"`
}

// Volunteer defines model for Volunteer.
type Volunteer struct {
	CreatedAt *time.Time `json:"createdAt,omitempty"`

	// Email Example: jonas@example.de
	Email *openapi_types.Email `json:"email,omitempty"`

	// FirstName Example: Jonas
	FirstName *string `json:"firstName,omitempty"`

	// Id Example: 5
	Id *int `json:"id,omitempty"`

	// IsActive Example: true
	IsActive *bool `json:"isActive,omitempty"`

	// LastName Example: Müller
	LastName *string `json:"lastName,omitempty"`

	// Phone Example: +49 170 1234567
	Phone *string `json:"phone,omitempty"`
}

// VolunteerCreate defines model for VolunteerCreate.
type VolunteerCreate struct {
	// Email Example: laura.schmidt@example.de
	Email openapi_types.Email `json:"email"`

	// FirstName Example: Laura
	FirstName string `json:"firstName"`

	// LastName Example: Schmidt
	LastName string `json:"lastName"`

	// Phone Example: +49 160 9876543
	Phone *string `json:"phone,omitempty"`
}

// VolunteerDetail defines model for VolunteerDetail.
type VolunteerDetail struct {
	AssignedShifts *[]ShiftAssignment `json:"assignedShifts,omitempty"`
	CreatedAt      *time.Time         `json:"createdAt,omitempty"`

	// Email Example: jonas@example.de
	Email *openapi_types.Email `json:"email,omitempty"`

	// FirstName Example: Jonas
	FirstName *string `json:"firstName,omitempty"`

	// Id Example: 5
	Id *int `json:"id,omitempty"`

	// IsActive Example: true
	IsActive *bool `json:"isActive,omitempty"`

	// LastName Example: Müller
	LastName *string `json:"lastName,omitempty"`

	// Phone Example: +49 170 1234567
	Phone *string `json:"phone,omitempty"`
}

// EditionIdParam defines model for EditionIdParam.
type EditionIdParam = int

// ShiftIdParam defines model for ShiftIdParam.
type ShiftIdParam = int

// VolunteerIdParam defines model for VolunteerIdParam.
type VolunteerIdParam = int

// BadRequest defines model for BadRequest.
type BadRequest = ErrorResponse

// NotFound defines model for NotFound.
type NotFound = ErrorResponse

// GetVolunteersParams defines parameters for GetVolunteers.
type GetVolunteersParams struct {
	// Search Filter nach Name oder E-Mail
	Search   *string `form:"search,omitempty" json:"search,omitempty"`
	IsActive *bool   `form:"isActive,omitempty" json:"isActive,omitempty"`
}

// PostWaffelCounterJSONBody defines parameters for PostWaffelCounter.
type PostWaffelCounterJSONBody struct {
	ShiftId *int `json:"shiftId,omitempty"`
}

// PatchAssignmentsAssignmentIdJSONRequestBody defines body for PatchAssignmentsAssignmentId for application/json ContentType.
type PatchAssignmentsAssignmentIdJSONRequestBody = AssignmentUpdate

// PostEditionsJSONRequestBody defines body for PostEditions for application/json ContentType.
type PostEditionsJSONRequestBody = EditionCreate

// PutEditionsEditionIdJSONRequestBody defines body for PutEditionsEditionId for application/json ContentType.
type PutEditionsEditionIdJSONRequestBody = EditionUpdate

// PostMarketDaysDayIdShiftsJSONRequestBody defines body for PostMarketDaysDayIdShifts for application/json ContentType.
type PostMarketDaysDayIdShiftsJSONRequestBody = ShiftCreate

// PostRolesJSONRequestBody defines body for PostRoles for application/json ContentType.
type PostRolesJSONRequestBody = RoleCreate

// PutShiftsShiftIdJSONRequestBody defines body for PutShiftsShiftId for application/json ContentType.
type PutShiftsShiftIdJSONRequestBody = ShiftCreate

// PostShiftsShiftIdAssignmentsJSONRequestBody defines body for PostShiftsShiftIdAssignments for application/json ContentType.
type PostShiftsShiftIdAssignmentsJSONRequestBody = AssignmentCreate

// PostVolunteersJSONRequestBody defines body for PostVolunteers for application/json ContentType.
type PostVolunteersJSONRequestBody = VolunteerCreate

// PutVolunteersVolunteerIdJSONRequestBody defines body for PutVolunteersVolunteerId for application/json ContentType.
type PutVolunteersVolunteerIdJSONRequestBody = VolunteerCreate

// PostWaffelCounterJSONRequestBody defines body for PostWaffelCounter for application/json ContentType.
type PostWaffelCounterJSONRequestBody PostWaffelCounterJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// DeleteAssignmentsAssignmentId Belegung austragen / stornieren
	// (DELETE /assignments/{assignmentId})
	DeleteAssignmentsAssignmentId(w http.ResponseWriter, r *http.Request, assignmentId int)
	// PatchAssignmentsAssignmentId Zuweisungsstatus oder Rolle ändern
	// (PATCH /assignments/{assignmentId})
	PatchAssignmentsAssignmentId(w http.ResponseWriter, r *http.Request, assignmentId int)
	// GetEditions Alle Editionen auflisten
	// (GET /editions)
	GetEditions(w http.ResponseWriter, r *http.Request)
	// PostEditions Neue Edition anlegen (z. B. neues Jahr)
	// (POST /editions)
	PostEditions(w http.ResponseWriter, r *http.Request)
	// GetEditionsActiveStandplan Standplan der aktuell aktiven Edition abrufen
	// (GET /editions/active/standplan)
	GetEditionsActiveStandplan(w http.ResponseWriter, r *http.Request)
	// GetEditionsEditionId Details einer Edition
	// (GET /editions/{editionId})
	GetEditionsEditionId(w http.ResponseWriter, r *http.Request, editionId EditionIdParam)
	// PutEditionsEditionId Edition bearbeiten (z. B. aktivieren)
	// (PUT /editions/{editionId})
	PutEditionsEditionId(w http.ResponseWriter, r *http.Request, editionId EditionIdParam)
	// GetEditionsEditionIdStandplan Vollständigen Schichtplan einer Edition abrufen
	// (GET /editions/{editionId}/standplan)
	GetEditionsEditionIdStandplan(w http.ResponseWriter, r *http.Request, editionId int)
	// GetMarketDaysDayIdShifts Alle Schichten eines bestimmten Tages abrufen
	// (GET /market-days/{dayId}/shifts)
	GetMarketDaysDayIdShifts(w http.ResponseWriter, r *http.Request, dayId int)
	// PostMarketDaysDayIdShifts Neue Schicht für einen Tag anlegen
	// (POST /market-days/{dayId}/shifts)
	PostMarketDaysDayIdShifts(w http.ResponseWriter, r *http.Request, dayId int)
	// GetRoles Liste möglicher Standrollen abrufen
	// (GET /roles)
	GetRoles(w http.ResponseWriter, r *http.Request)
	// PostRoles Neue Standrolle anlegen
	// (POST /roles)
	PostRoles(w http.ResponseWriter, r *http.Request)
	// DeleteShiftsShiftId Schicht löschen
	// (DELETE /shifts/{shiftId})
	DeleteShiftsShiftId(w http.ResponseWriter, r *http.Request, shiftId ShiftIdParam)
	// GetShiftsShiftId Einzelne Schicht inklusive Belegungsstatus abrufen
	// (GET /shifts/{shiftId})
	GetShiftsShiftId(w http.ResponseWriter, r *http.Request, shiftId ShiftIdParam)
	// PutShiftsShiftId Schichtzeiten oder Slot-Bedarf anpassen
	// (PUT /shifts/{shiftId})
	PutShiftsShiftId(w http.ResponseWriter, r *http.Request, shiftId ShiftIdParam)
	// PostShiftsShiftIdAssignments Helfer in eine Schicht eintragen
	// (POST /shifts/{shiftId}/assignments)
	PostShiftsShiftIdAssignments(w http.ResponseWriter, r *http.Request, shiftId ShiftIdParam)
	// GetVolunteers Helferliste abrufen
	// (GET /volunteers)
	GetVolunteers(w http.ResponseWriter, r *http.Request, params GetVolunteersParams)
	// PostVolunteers Neuen Helfer registrieren
	// (POST /volunteers)
	PostVolunteers(w http.ResponseWriter, r *http.Request)
	// GetVolunteersVolunteerId Helferprofil und persönliche Schichten anzeigen
	// (GET /volunteers/{volunteerId})
	GetVolunteersVolunteerId(w http.ResponseWriter, r *http.Request, volunteerId VolunteerIdParam)
	// PutVolunteersVolunteerId Helferdaten aktualisieren
	// (PUT /volunteers/{volunteerId})
	PutVolunteersVolunteerId(w http.ResponseWriter, r *http.Request, volunteerId VolunteerIdParam)
	// DeleteWaffelCounter Waffelzähler zurücksetzen
	// (DELETE /waffel-counter)
	DeleteWaffelCounter(w http.ResponseWriter, r *http.Request)
	// GetWaffelCounter Aktuelle Waffelanzahl abrufen
	// (GET /waffel-counter)
	GetWaffelCounter(w http.ResponseWriter, r *http.Request)
	// PostWaffelCounter Eine Waffel zum Zähler hinzufügen
	// (POST /waffel-counter)
	PostWaffelCounter(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// DeleteAssignmentsAssignmentId operation middleware
func (siw *ServerInterfaceWrapper) DeleteAssignmentsAssignmentId(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "assignmentId" -------------
	var assignmentId int

	err = runtime.BindStyledParameterWithOptions("simple", "assignmentId", r.PathValue("assignmentId"), &assignmentId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "assignmentId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteAssignmentsAssignmentId(w, r, assignmentId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PatchAssignmentsAssignmentId operation middleware
func (siw *ServerInterfaceWrapper) PatchAssignmentsAssignmentId(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "assignmentId" -------------
	var assignmentId int

	err = runtime.BindStyledParameterWithOptions("simple", "assignmentId", r.PathValue("assignmentId"), &assignmentId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "assignmentId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PatchAssignmentsAssignmentId(w, r, assignmentId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetEditions operation middleware
func (siw *ServerInterfaceWrapper) GetEditions(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetEditions(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostEditions operation middleware
func (siw *ServerInterfaceWrapper) PostEditions(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostEditions(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetEditionsActiveStandplan operation middleware
func (siw *ServerInterfaceWrapper) GetEditionsActiveStandplan(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetEditionsActiveStandplan(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetEditionsEditionId operation middleware
func (siw *ServerInterfaceWrapper) GetEditionsEditionId(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "editionId" -------------
	var editionId EditionIdParam

	err = runtime.BindStyledParameterWithOptions("simple", "editionId", r.PathValue("editionId"), &editionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "editionId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetEditionsEditionId(w, r, editionId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PutEditionsEditionId operation middleware
func (siw *ServerInterfaceWrapper) PutEditionsEditionId(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "editionId" -------------
	var editionId EditionIdParam

	err = runtime.BindStyledParameterWithOptions("simple", "editionId", r.PathValue("editionId"), &editionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "editionId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PutEditionsEditionId(w, r, editionId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetEditionsEditionIdStandplan operation middleware
func (siw *ServerInterfaceWrapper) GetEditionsEditionIdStandplan(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "editionId" -------------
	var editionId int

	err = runtime.BindStyledParameterWithOptions("simple", "editionId", r.PathValue("editionId"), &editionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "editionId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetEditionsEditionIdStandplan(w, r, editionId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetMarketDaysDayIdShifts operation middleware
func (siw *ServerInterfaceWrapper) GetMarketDaysDayIdShifts(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "dayId" -------------
	var dayId int

	err = runtime.BindStyledParameterWithOptions("simple", "dayId", r.PathValue("dayId"), &dayId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "dayId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMarketDaysDayIdShifts(w, r, dayId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostMarketDaysDayIdShifts operation middleware
func (siw *ServerInterfaceWrapper) PostMarketDaysDayIdShifts(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "dayId" -------------
	var dayId int

	err = runtime.BindStyledParameterWithOptions("simple", "dayId", r.PathValue("dayId"), &dayId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "dayId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostMarketDaysDayIdShifts(w, r, dayId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetRoles operation middleware
func (siw *ServerInterfaceWrapper) GetRoles(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetRoles(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostRoles operation middleware
func (siw *ServerInterfaceWrapper) PostRoles(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostRoles(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteShiftsShiftId operation middleware
func (siw *ServerInterfaceWrapper) DeleteShiftsShiftId(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "shiftId" -------------
	var shiftId ShiftIdParam

	err = runtime.BindStyledParameterWithOptions("simple", "shiftId", r.PathValue("shiftId"), &shiftId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "shiftId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteShiftsShiftId(w, r, shiftId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetShiftsShiftId operation middleware
func (siw *ServerInterfaceWrapper) GetShiftsShiftId(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "shiftId" -------------
	var shiftId ShiftIdParam

	err = runtime.BindStyledParameterWithOptions("simple", "shiftId", r.PathValue("shiftId"), &shiftId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "shiftId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetShiftsShiftId(w, r, shiftId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PutShiftsShiftId operation middleware
func (siw *ServerInterfaceWrapper) PutShiftsShiftId(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "shiftId" -------------
	var shiftId ShiftIdParam

	err = runtime.BindStyledParameterWithOptions("simple", "shiftId", r.PathValue("shiftId"), &shiftId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "shiftId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PutShiftsShiftId(w, r, shiftId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostShiftsShiftIdAssignments operation middleware
func (siw *ServerInterfaceWrapper) PostShiftsShiftIdAssignments(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "shiftId" -------------
	var shiftId ShiftIdParam

	err = runtime.BindStyledParameterWithOptions("simple", "shiftId", r.PathValue("shiftId"), &shiftId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "shiftId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostShiftsShiftIdAssignments(w, r, shiftId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetVolunteers operation middleware
func (siw *ServerInterfaceWrapper) GetVolunteers(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params GetVolunteersParams

	// ------------- Optional query parameter "search" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "search", r.URL.Query(), &params.Search, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "search"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "search", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "isActive" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "isActive", r.URL.Query(), &params.IsActive, runtime.BindQueryParameterOptions{Type: "boolean", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "isActive"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "isActive", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetVolunteers(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostVolunteers operation middleware
func (siw *ServerInterfaceWrapper) PostVolunteers(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostVolunteers(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetVolunteersVolunteerId operation middleware
func (siw *ServerInterfaceWrapper) GetVolunteersVolunteerId(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "volunteerId" -------------
	var volunteerId VolunteerIdParam

	err = runtime.BindStyledParameterWithOptions("simple", "volunteerId", r.PathValue("volunteerId"), &volunteerId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "volunteerId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetVolunteersVolunteerId(w, r, volunteerId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PutVolunteersVolunteerId operation middleware
func (siw *ServerInterfaceWrapper) PutVolunteersVolunteerId(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "volunteerId" -------------
	var volunteerId VolunteerIdParam

	err = runtime.BindStyledParameterWithOptions("simple", "volunteerId", r.PathValue("volunteerId"), &volunteerId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "volunteerId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PutVolunteersVolunteerId(w, r, volunteerId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteWaffelCounter operation middleware
func (siw *ServerInterfaceWrapper) DeleteWaffelCounter(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteWaffelCounter(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetWaffelCounter operation middleware
func (siw *ServerInterfaceWrapper) GetWaffelCounter(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetWaffelCounter(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostWaffelCounter operation middleware
func (siw *ServerInterfaceWrapper) PostWaffelCounter(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostWaffelCounter(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/editions/{editionId}/standplan", wrapper.GetEditionsEditionIdStandplan)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/editions/active/standplan", wrapper.GetEditionsActiveStandplan)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/editions", wrapper.GetEditions)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/editions", wrapper.PostEditions)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/editions/{editionId}", wrapper.GetEditionsEditionId)
	m.HandleFunc(http.MethodPut+" "+options.BaseURL+"/editions/{editionId}", wrapper.PutEditionsEditionId)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/market-days/{dayId}/shifts", wrapper.GetMarketDaysDayIdShifts)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/market-days/{dayId}/shifts", wrapper.PostMarketDaysDayIdShifts)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/shifts/{shiftId}", wrapper.DeleteShiftsShiftId)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/shifts/{shiftId}", wrapper.GetShiftsShiftId)
	m.HandleFunc(http.MethodPut+" "+options.BaseURL+"/shifts/{shiftId}", wrapper.PutShiftsShiftId)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/volunteers", wrapper.GetVolunteers)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/volunteers", wrapper.PostVolunteers)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/volunteers/{volunteerId}", wrapper.GetVolunteersVolunteerId)
	m.HandleFunc(http.MethodPut+" "+options.BaseURL+"/volunteers/{volunteerId}", wrapper.PutVolunteersVolunteerId)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/shifts/{shiftId}/assignments", wrapper.PostShiftsShiftIdAssignments)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/assignments/{assignmentId}", wrapper.DeleteAssignmentsAssignmentId)
	m.HandleFunc(http.MethodPatch+" "+options.BaseURL+"/assignments/{assignmentId}", wrapper.PatchAssignmentsAssignmentId)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/roles", wrapper.GetRoles)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/roles", wrapper.PostRoles)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/waffel-counter", wrapper.DeleteWaffelCounter)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/waffel-counter", wrapper.GetWaffelCounter)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/waffel-counter", wrapper.PostWaffelCounter)

	return m
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"zFtLd9u2tv4ruLwdOOvqaTtJq8m9cm3nps1rRWmyVh2fsyByk0QEgioA2pV89E/OsL8hI8/0x84CwDdB",
	"PRzb6Uyk8Pz23t9+ALxx3DiaxwyYFM7oxpljjiOQwPXTmUckidlL7516rd4Q5oycOZah03EYjsAZOZA1",
	"cjoOhz8SwsFzRpIn0HGEG0KEVUe5mKvGhEkIgDurVceZhMSXm8cWpsm+I3+MacIkAN88+lXRbL8ZVqq1",
	"mMdMgMbpBHvv4Y8EhFRPbswkMP0Tz+eUuFjh0/8iYqbeFeP+wMF3Rs5/9wsZ9M2/on/Geczfp5OYKT0Q",
	"LidzNZgzcn5jwfqWShIAOiMswFPwsATmrDrOm1iexwnzHm8x70GIOOEuIEbcUKIA/IR5ajWrDEgN1FgI",
	"ErAImPyZA5agVY7Hc+CSGCh5TOGlXjn8iaM5BWd02HFYQimeqgcjm7pEOo6QWCZ6BA98nFDpjNTefcIj",
	"UNIFlkTO6MKZA/MIC5xO5V8XMxcoBc+5zAcXkquGq05FT8oLe9qxKV+hRxeVnsXI8fQLuFKNXODx29zb",
	"gsc+GNx9tyvLKlMaaC7O1UL0xlq9/JhHWMGuNtKVJALHgiWpQji07YOIsSvJFVRaVjY9jWMKWCu7seVS",
	"Q+cTkJBhN5Qiwnwm0eHg8JltKQvAvKpog8NnVpG2IdKmxOUN5OroYyq+2w7KSql7pdNetm+uTSPLm2vf",
	"zC5qVWGVxjyg/q7i8ubth3+ev/3tzakNjAiEwEENyVMCKACRuKEENHFDzU7wJxGSAJeGrXqOzQrKiJml",
	"FFPYUHsfU8smKjRZXtivWAgCHFgHfQI3FEADoB66An6NqQSGEuah8ZSDG7JEW3CL/bea1qHNtJq6phYC",
	"6HMyGBw+Qx+Bz3DiOzvRgtpxmwXU9t1Yq0Xnse8DBSKAbZVHq+rqkMKyGrwwHNoEBJj3gdTXMnw+OhqM",
	"BgOnoyIGCVz5uH8cXAyGl58/e/86vBh0jy6fjC4G3afqxUH+68n//rAL6Q2soollqvj5Ok6IlICGT9Fr",
	"whKlFFcxRycQEMaQh5EAwv5rF83IsJvQWFanOO44EWEkUu5i2OJTuLQgdDwa3CdCkkham2Kc+FOcZJp5",
	"zte3oTAGvJt6al0oHGxTK7D+79vc18AKGk+5YFNMpfkibbuzg0/DYasm38n7F3CXm7RHQNt2lUfelrhp",
	"F8eqhdZGKlZbPRyOjga2Nef29A3mcXRX8/jR2MYuej6Zr/+SqWajF3R9G14D2c6BZqTyCgoyq2+plSpP",
	"QWJCtTFQ+tZ3RhebxWv4ddWxm1KUZZFEQiS2qUrdPgt1wJzjhXr2OUBTKFZBxK6bzEmLDLdr3qVCRGLm",
	"zSlmp3hh8yGyrnmDw2fd4bB7+NzpVOnDJnkPL976nwBmZQs950AkVhY6wZFIf8WMqV+XrfTTQgx7Qp/K",
	"vgG71SwzaDaEa0WSsDGVTJutOs41wAyYt8eys1V8Mj33XHvWyxYe3GERp0ZH6zrbJiKKp0BrLNFDY+9K",
	"jX4duyEwYJ5VdVKg3iTRFPg2U7BB8LFM39+cwkGUckaxky8xw+L/0uee3kU+lmluGccnXMg3jUDwFzXW",
	"Dr736TenjhTb5n+9vqUUuG0F8zBmtdb/c/wTGj4foOHh0fHTZ8+3R2Mb5dPq+ZqQU5xw3BNuGBFP3hP0",
	"r9SYtvZ2pCZm8n2QejZAP/34/NnT46OtDq5YY2n+TPsuN6G4r1crBy1tQeLkDgy7ybnZXJAicnATTuRi",
	"osZJi4uAOfBxIkP1NNVP55mEf/n0wUkrbFq59b8FtKGUc1OvI8yPG4mZM373Ei0TrvI+lXYmLNB55ykJ",
	"iMSUqAxVvfNAZMmzYj6B/PUtRx4wVKtUCEWOvc9sInkykwkfoSFKGR8d/IJD/gR1VUB/BOgIfcpJj+Vv",
	"v6g/PuAA0ME576AJ7qBJXHTyKfxJpjRP5YGhiEj0/0B94CZnfh9TCqz3WUdQJtpq1FNyDkfjdy+djnMF",
	"XBhADnuD3kDHE3NgeE6ckXPUG/SOTJ4TaoH0S9FO/6Z4eOmtDMIUjA0rPcJpbXzknOr3hU6IcamnHr8o",
	"vV9Y69W42mGPgvVlrWB9ODhuKsMJUAiUuIH7MQ04EDdEAdD1V6GSLq2eSRRhvig3xomQHAfAUB8JGXOm",
	"qxoKfByonTipqKZpB2COCrbmWLphE6R36vV3xEgX8U9ib3FvtfNGiXdVJTq1rlVDPIN7m7/BRKtVmWg0",
	"jmWKubhUSBSC/j25BiISFgiTYKLYA26sDK3/Yp5K/TcLe9Vx+ml0qHcXgGwK/gXIs6zNN6KxE0GX4tAa",
	"MTcON14RIQFhFRQgxWGQdc7ON3KsxgqU/E+EE5+qvmWAiq7aCmJhweJdLKpg3L9WVgvYu6jkcHDfk9uw",
	"zpxFmYKACwmUaid6bHTBNnq+3H7pOG4vVX8DSS4+hBkFxWoHyx466SEGCQgt/ict0iyreR/rKLQvMkdT",
	"0vvqhiduyIBSIExIAkHqWbEwPqr7QUWSUjs2jwBaf/V9YJISN4TU63XX/54q95UWslutysTFuedzHpJy",
	"GtmiRdLjmUxA2xSeqZXxwisbQVs81K9AGKTtc0FVzxpzYRY+3jNzqNnSvqyQ8pQnftVd5auoifQmP+he",
	"7cJiZ6Vj8ZrbsmFXNOnXTt0tzvtBTLEAfbN15afLVbxN0C2QEhHP8G0nvsTGe8lDofdgBPp9fHpZavsQ",
	"XKb1Kk2YApEFvWm70JHbTvRWsoUdOO4VAR+41AnDLFbpoFRThwQ45m5I1LZYKSg/sGUGOinIHorwP3tz",
	"kkccT1IOJYBecOJ1x2w7OeZKU+bH7cHmHa++XH5v7v0YUyqkit5I0EK8d+KAyrisnDJWaWEH2lWJGsiu",
	"hxeif6PP71b9osrZRr6vda9TvBCnqkuatO8iSnNE+Khi3L2QYItSLZFnYRUKbYGmICSJIvVCWY+wwZ51",
	"2RKOPj6w90/Z5bOlnQh7eL9T703XOh7NLi1oUlNy1cLMwtMWUSoL4jGFjcbyXjd4DCXOzjo367DJs6L1",
	"10DHtykvcV3PsaiuKfRs0dtij/evT6X7D4+sTgbPO2lTDqlFg3JElfoYsu3fpGfOO5S2DClM8iub+8Vt",
	"lduguxWsMtOo1ah2BSTrbjpvoMU2A3rYDd9zCSg77vvmQP+MsCVQVjATYTOaCJWSZUFYVira6m9asoB7",
	"B/Zv4EwG39mZpMgvTdivi3gTGsvuCXiY+wizORZio0OpM0K/duqfsXDVSD8BETJ1XKZikcaCmfoskx56",
	"x9e3vkQ+BwJ6WUKXPK6Ah4R5OneI53OgElBejwTWDOkV5VeUp1RK/nvqUeNG9PeITKrl4Xq2kCO+rSpn",
	"Z2cl/ilwIFKgq5hSpIvD0qhgUtxiz6cxI/7UHDFVHzWgR0CUdCgbf5kEcK3+qleDsq4mNC5ughJmDi92",
	"KGHnt5k2BlUfi1YNfavu5pxQCRwx7IboDY7AAHLWfW3ObHUo/UcCfFH6HAJUvuxYgufiDPXG2jM/Fy/3",
	"za8m2w/IHyfBqdwYswaIuzKckTE11fqG5zH/bgkXK9J7CHOvn/Q/srWXwE7jAIuZGRXsjj0OQkDptnRq",
	"ZTXTUnFlTu0cAqJ0sXYGmINfNaT+TemK4Go3s/pY+WhnP0ZvfBf0oGFX/T7Ct4deBsY5j31CtYOcAxfr",
	"r8ycBxTpP2ZLIEGr+rdEXQ+K8d/ElAYPZEr785T+WkufS6QXLdoN5lpfje+6sZqQb0/EzFX6n9Pmu2RS",
	"psdy/VdIgat8CoDvmU1Vh1gmfH3rzgTIZWVfplU3W9um7GrLLvaTZO1SD1visHqf6uj4cJe7dI26W3qK",
	"hcxqzcAW72PZd7sXau78btZT3XTp8vi2m+bWfdslYNOj2gUSrROymUVmoKFlEqHfU8UJCVsm/vo22Ayf",
	"UU1+ZQ+tXsUzrAY7Y/KauDOqU1Ld2uk4CafpzSgx6vfxnPQ8uOpFiy+iF/OgfzXUjJXO3LgwFQTKxQGX",
	"gF6AwJHEU99cfylObouyd/c9FkaGaRxWLrXXxy5dwlKR4GvMZ7KrLxygg/wk5kkxVukWQmOs8gnKwbB7",
	"9ES7Cz2kTG9X6ZvHHZRePO6g9N5xaYLyIOlnGB9wAJbpqtexsltaLP1WpdtBZ8xLM0+1Dp14jo0RFtDk",
	"6WZz/F9jJvFMGs5UI3wErpRkivnMDKsQU+njNaFUHz6kDJoPnz43xy7Sm6uYWa6SoWVSuNbGcktpggWW",
	"UgEzPWjTn1t1UOlrp05x6R8nQrghZrOOKdRRIEodSiJJS3SWXaT2o7XwynzGJTMLYwhHZkR08AoC7C66",
	"54BlwqEs7aqNrS5X/wkAAP//",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
